name = "curve25519-dalek"
version = "0.1.0"
keywords = ["formal verification"]
defaultTargets = ["Curve25519Dalek", "Proofs"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxRecDepth = 10000

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "60228043"

# Hand-written models for the `subtle` crate.
[[lean_lib]]
name = "Subtle"
srcDir = "curve25519-dalek/lean"

# Aeneas-generated Lean translation.
[[lean_lib]]
name = "Curve25519Dalek"
srcDir = "curve25519-dalek/lean"

# Hand-written proofs.
[[lean_lib]]
name = "Proofs"
srcDir = "curve25519-dalek/lean"
